# Generated by Django 5.2.1 on 2025-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('product_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_in_market', models.PositiveIntegerField(default=0, verbose_name='Yillar bozorda')),
                ('satisfied_clients', models.PositiveIntegerField(default=0, verbose_name='Mamnun mijozlar')),
                ('installed_items_km', models.FloatField(default=0, verbose_name="O'rnatilgan panjaralar (km)")),
                ('work_all_days', models.PositiveIntegerField(default=0, verbose_name='Ish kunlari minimal')),
            ],
        ),
    ]
