# Generated by Django 5.2.1 on 2025-05-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
